### ISSUE TITLE
Mobile view is not responsive

### ISSUE THREAD

**Issue by mlordi** [Muetze42/nova-resource-card#8]
When I load this on my mobile phone it stretches the view to fit instead of becoming a scrollable table. Is there a way to make this responsive?

**Comment by Muetze42** [comment]
OK. But I will most probably manage to watch it at the weekend.

**Comment by mlordi** [comment]
> OK. But I will most probably manage to watch it at the weekend.

No problem. Thanks for the help!

**Comment by Muetze42** [comment]
Fixed with version 1.0.3+

https://github.com/Muetze42/nova-resource-card/releases
